### ISSUE TITLE
Transaction date column

### ISSUE THREAD

**Issue by moraisz** [kelidss/My-Finances-Java#5]
# About the problem

The transaction model does not have the transaction date column.

## ToDo

- Create a column with `private LocalDateTime transaction_date;` and create getter and setter to this parameter.

![image](https://github.com/user-attachments/assets/d18030fd-f41c-47f8-9ed4-71f5a96fa019)

**Comment by kelidss** [comment]
now we save the creation date automatically:


![image](https://github.com/user-attachments/assets/a81b62e1-f06a-4d4f-b115-f9727b6286d8)

**Comment by kelidss** [comment]
Thanks for the feedback, I'm making improvements to the filter before sending it to main
